[package]
name = "os-checker-test-suite"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = ["buildrs-failure", "lockbud-checks-this", "mirai-checks-this", "miri-checks-this", "rap-checks-this", "rudra-checks-this"]
exclude = ["workspace2"]
